# Copyright Greg Haskins All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
FROM _BASE_NS_/blockchain-runenv:_BASE_TAG_
COPY payload/orderer /usr/local/bin
RUN mkdir -p /etc/rongzer/blockchain && \
    mkdir -p /var/rongzer/production
ADD payload/sampleconfig.tar.bz2 /etc/rongzer/blockchain
ENV BLOCKCHAIN_CFG_PATH /etc/rongzer/blockchain
EXPOSE 7050
CMD ["orderer"]